### ISSUE TITLE
Support Swift 3

### ISSUE THREAD

**Issue by Vitaliyy-jomedia** [mariohahn/StatusProvider#7]
When do you plan to implement support for Swift 3?

**Comment by mariohahn** [comment]
Swift 3 is already supported. Just check the master branch, i haven't updated the Pod yet. 

Use this atm pls:  pod 'StatusProvider', :git => 'https://github.com/mariohahn/StatusProvider.git', :branch => 'master'

**Comment by mariohahn** [comment]
🎉  Congrats

 🚀  StatusProvider (1.1.1) successfully published
 📅  November 2nd, 14:05

**Comment by Vitaliyy-jomedia** [comment]
Yes, it works.
Thanks for the quick response.

**Comment by mariohahn** [comment]
you can now use: "pod 'StatusProvider' " only because i published the new Version to Cocoapods

**Comment by Vitaliyy-jomedia** [comment]
Yes, I understand it.
Thank you.
