### ISSUE TITLE
Carthage？

### ISSUE THREAD

**Issue by pangpingfei** [mariohahn/StatusProvider#9]
Hope

**Comment by ghost** [comment]
+1

**Comment by EternalBlack** [comment]
+1

**Comment by mariohahn** [comment]
248bff8c442cae17d6a28666dbedff5793dd8ba7

**Comment by mariohahn** [comment]
Is it working for you now? I am not really a Carthage User :D

**Comment by EternalBlack** [comment]
Oh, I had just read the readme.md and didn't check the commits.
Carthage does work, thank you so far. But unfortunately adding this to a tableview ain't as easy as expected. But thats another story.

**Comment by mariohahn** [comment]
Any Problems? I always use it for table views? if yes create me an issue (:

**Comment by pangpingfei** [comment]
Tks~!
